import { NextResponse } from "next/server";
import { cookies } from "next/headers";
import { prisma } from "@/lib/prisma";
import { verifyAuthToken } from "@/lib/auth";
import { can } from "@/lib/admin/permissions";

const categories = ["Dating Advice", "Relationships", "Love & Marriage", "Dating Safety", "Liberia", "Long Distance Relationships", "Dating Abroad", "Success Stories"];
async function getAdmin() { const token = (await cookies()).get("love_liberia_token")?.value; const userId = token ? await verifyAuthToken(token) : null; if (!userId) return null; const user = await prisma.user.findUnique({ where: { id: userId }, select: { id: true, role: true } }); return user && can(user.role, "manage_content") ? user : null; }
function slugify(value: string) { return value.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); }

export async function GET() { const admin = await getAdmin(); if (!admin) return NextResponse.json({ error: "Content manager access required." }, { status: 403 }); const articles = await prisma.blogArticle.findMany({ where: { deletedAt: null }, orderBy: { updatedAt: "desc" }, include: { author: { select: { firstName: true, username: true } } } }); return NextResponse.json({ articles }); }

export async function POST(request: Request) { const admin = await getAdmin(); if (!admin) return NextResponse.json({ error: "Content manager access required." }, { status: 403 }); const body = await request.json(); if (typeof body.title !== "string" || !body.title.trim() || typeof body.excerpt !== "string" || typeof body.content !== "string" || !categories.includes(body.category)) return NextResponse.json({ error: "Title, excerpt, content, and valid category are required." }, { status: 400 }); const baseSlug = typeof body.slug === "string" && body.slug.trim() ? slugify(body.slug) : slugify(body.title); const slug = `${baseSlug}-${Date.now().toString(36)}`; const status = body.status === "PUBLISHED" ? "PUBLISHED" : "DRAFT"; const article = await prisma.blogArticle.create({ data: { authorId: admin.id, title: body.title.trim().slice(0, 180), slug, excerpt: body.excerpt.trim().slice(0, 500), content: body.content.trim(), category: body.category, coverImage: typeof body.coverImage === "string" ? body.coverImage.slice(0, 2048) : null, status, publishedAt: status === "PUBLISHED" ? new Date() : null } }); return NextResponse.json({ article }, { status: 201 }); }

export async function PATCH(request: Request) { const admin = await getAdmin(); if (!admin) return NextResponse.json({ error: "Content manager access required." }, { status: 403 }); const body = await request.json(); if (typeof body.id !== "string") return NextResponse.json({ error: "Article ID is required." }, { status: 400 }); const status = body.status === "PUBLISHED" ? "PUBLISHED" : "DRAFT"; const article = await prisma.blogArticle.update({ where: { id: body.id }, data: { ...(typeof body.title === "string" ? { title: body.title.trim().slice(0, 180) } : {}), ...(typeof body.excerpt === "string" ? { excerpt: body.excerpt.trim().slice(0, 500) } : {}), ...(typeof body.content === "string" ? { content: body.content.trim() } : {}), ...(categories.includes(body.category) ? { category: body.category } : {}), ...(typeof body.coverImage === "string" ? { coverImage: body.coverImage.slice(0, 2048) } : {}), status, publishedAt: status === "PUBLISHED" ? new Date() : null } }); return NextResponse.json({ article }); }

export async function DELETE(request: Request) { const admin = await getAdmin(); if (!admin) return NextResponse.json({ error: "Content manager access required." }, { status: 403 }); const id = new URL(request.url).searchParams.get("id"); if (!id) return NextResponse.json({ error: "Article ID is required." }, { status: 400 }); await prisma.blogArticle.update({ where: { id }, data: { deletedAt: new Date(), status: "ARCHIVED" } }); return NextResponse.json({ success: true }); }
