"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, Gift, Loader2, Sparkles, WalletCards } from "lucide-react";

type Commerce = { transactions: { id: string; userId: string; type: string; credits: number; amountCents: number; status: string; createdAt: string }[]; gifts: { id: string; senderId: string; receiverId: string; giftType: string; credits: number; createdAt: string }[]; subscriptions: { id: string; firstName: string; username: string; membershipPlan: string; membershipStatus: string }[] };

export default function AdminCommercePage() {
  const [data, setData] = useState<Commerce | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { fetch("/api/admin/commerce", { cache: "no-store" }).then(async (response) => { const result = await response.json(); if (!response.ok) { setError(result.error || "Unable to load commerce."); return; } setData(result); }).catch(() => setError("Unable to load commerce.")); }, []);
  if (!data && !error) return <main className="flex min-h-screen items-center justify-center bg-slate-100"><Loader2 className="h-8 w-8 animate-spin text-rose-600" /></main>;
  return <main className="min-h-screen bg-slate-100 px-5 py-8 text-slate-950 sm:px-8"><div className="mx-auto max-w-7xl"><Link href="/admin" className="flex items-center gap-2 text-sm font-bold text-rose-600"><ArrowLeft className="h-4 w-4" />Admin dashboard</Link><h1 className="mt-5 text-3xl font-black">Commerce management</h1><p className="mt-2 text-slate-600">Review subscriptions, purchases, gifts, and credit adjustments.</p>{error && <p className="mt-6 rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}{data && <div className="mt-8 grid gap-5 lg:grid-cols-3"><section className="bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><Sparkles className="h-5 w-5 text-rose-600" /><h2 className="font-black">Subscriptions</h2></div><p className="mt-4 text-3xl font-black">{data.subscriptions.length}</p><p className="text-sm text-slate-500">Premium and VIP accounts</p><div className="mt-5 space-y-2">{data.subscriptions.slice(0, 8).map((item) => <p key={item.id} className="flex justify-between text-sm"><span>@{item.username}</span><b>{item.membershipPlan}</b></p>)}</div></section><section className="bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><WalletCards className="h-5 w-5 text-amber-600" /><h2 className="font-black">Credit purchases</h2></div><p className="mt-4 text-3xl font-black">{data.transactions.length}</p><p className="text-sm text-slate-500">Recent wallet activity</p><div className="mt-5 space-y-2">{data.transactions.slice(0, 8).map((item) => <p key={item.id} className="flex justify-between text-sm"><span>{item.type}</span><b className={item.credits < 0 ? "text-red-600" : "text-emerald-600"}>{item.credits > 0 ? "+" : ""}{item.credits}</b></p>)}</div></section><section className="bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><Gift className="h-5 w-5 text-violet-600" /><h2 className="font-black">Gifts and boosts</h2></div><p className="mt-4 text-3xl font-black">{data.gifts.length}</p><p className="text-sm text-slate-500">Virtual gifts sent</p><div className="mt-5 space-y-2">{data.gifts.slice(0, 8).map((item) => <p key={item.id} className="flex justify-between text-sm"><span>{item.giftType}</span><b>{item.credits} credits</b></p>)}</div></section></div>}</div></main>;
}
